services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich_server
    restart: unless-stopped
    ports:
      - "2283:2283"
    environment:
      DB_HOSTNAME: immich_postgres
      DB_USERNAME: postgres
      DB_DATABASE_NAME: immich
      DB_PASSWORD: "${DB_PASSWORD}"
      REDIS_HOSTNAME: immich_redis
      TZ: Europe/Rome
    volumes:
      - /mnt/immich/data:/usr/src/app/upload
    depends_on:
      - immich-postgres
      - immich-redis

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: immich_machine_learning
    restart: unless-stopped
    environment:
      TZ: Europe/Rome
    volumes:
      - /mnt/immich/cache:/cache
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128

  immich-postgres:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    container_name: immich_postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - /mnt/immich/db:/var/lib/postgresql/data

  immich-redis:
    image: redis:6.2-alpine
    container_name: immich_redis
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping || exit 1

  portainer-agent:
    image: portainer/agent:latest
    container_name: portainer-agent
    restart: unless-stopped
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
