package tunnel

import (
	"bytes"
	"errors"
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"
)

// ErrNoDomain is returned when rendering is attempted without a public domain
// to substitute. Rendering anyway would write real hostnames into a public repo.
var ErrNoDomain = errors.New("public_domain is empty: refusing to render, the real domain would be written verbatim")

// ErrNilConfig is returned by Render and UnexpectedDomains when called with a
// nil *TunnelConfig, so callers get a clear error instead of a panic.
var ErrNilConfig = errors.New("tunnel config is nil: nothing to render")

const renderHeader = `# Generated by ` + "`infra tunnel export`" + ` — DO NOT EDIT BY HAND.
#
# This is a MIRROR of a remotely-managed Cloudflare tunnel. The Zero Trust
# dashboard is the source of truth; editing this file changes nothing there.
#
# Regenerate:      infra tunnel export
# Check for drift: infra tunnel diff
#
# The real domain is replaced with ` + DomainPlaceholder + ` because this repo is
# public. The real value lives in ~/.config/infra/cloudflare.yml and CLAUDE.local.md.
`

// normaliseDomain lowercases publicDomain, trims surrounding whitespace, and
// strips leading/trailing dots, so that ".example.test", " EXAMPLE.test ", and
// "example.test" are all treated identically. Render and UnexpectedDomains
// each normalise once, at the top, and use only the returned value thereafter
// — nothing downstream should see the raw, untrimmed, case-sensitive input.
func normaliseDomain(publicDomain string) string {
	d := strings.ToLower(strings.TrimSpace(publicDomain))
	return strings.Trim(d, ".")
}

// onDomain reports whether hostname is normalisedDomain itself, or a subdomain
// of it (e.g. "*.example.test" or "foo.example.test" for domain
// "example.test"), compared case-insensitively because DNS names are not
// case-sensitive. normalisedDomain must already be the output of
// normaliseDomain.
//
// This is the single predicate substituteDomain and UnexpectedDomains both
// call. Do not re-implement this check anywhere else — a second copy that
// drifts from this one is exactly how a hostname ends up neither substituted
// nor reported, which is a silent leak.
func onDomain(hostname, normalisedDomain string) bool {
	if normalisedDomain == "" || hostname == "" {
		return false
	}
	h := strings.ToLower(hostname)
	return h == normalisedDomain || strings.HasSuffix(h, "."+normalisedDomain)
}

// Render serialises cfg to deterministic YAML with publicDomain replaced by
// DomainPlaceholder wherever it appears as a hostname.
//
// Determinism matters: `infra tunnel diff` compares bytes, so any instability
// here shows up as phantom drift. Struct field order fixes key order, and
// yaml.v3 sorts map keys, which covers originRequest and warp-routing.
//
// Hostname substitution is not the last word: after marshalling, the output
// is scanned byte-for-byte for the domain and the render is rejected if it is
// still present anywhere (see the guard below). That closes the gap left by
// fields substituteDomain deliberately does not touch — Service, Path, and
// OriginRequest values — and by any hostname substitution failed to fully
// strip.
func Render(cfg *TunnelConfig, publicDomain string) ([]byte, error) {
	domain := normaliseDomain(publicDomain)
	if domain == "" {
		return nil, ErrNoDomain
	}
	if cfg == nil {
		return nil, ErrNilConfig
	}

	sanitised := *cfg
	// Shallow copy: WarpRouting, the top-level OriginRequest, and each
	// Ingress[i].OriginRequest map below are shared by reference with the
	// caller's cfg, not deep-copied. That is safe only because nothing here
	// writes into any of those maps — only the value-typed Hostname field of
	// the per-element Ingress copy is rewritten. If a future change starts
	// writing into WarpRouting/OriginRequest (e.g. to sanitise a hostname
	// found there), it will silently mutate the caller's config too, which
	// would poison the later `diff` comparison. Deep-copy first if that's ever
	// needed.
	sanitised.Ingress = make([]Ingress, len(cfg.Ingress))
	for i, in := range cfg.Ingress {
		in.Hostname = substituteDomain(in.Hostname, domain)
		sanitised.Ingress[i] = in
	}
	body, err := yaml.Marshal(&sanitised)
	if err != nil {
		return nil, fmt.Errorf("marshal tunnel config: %w", err)
	}
	out := append([]byte(renderHeader+"\n"), body...)

	// Fail closed: if the real domain is still in the rendered bytes anywhere
	// — case-insensitively — after hostname substitution, do not return them.
	// substituteDomain only ever touches Ingress.Hostname; it deliberately
	// does not attempt to rewrite Service, Path, or OriginRequest values,
	// since guessing at their structure risks corrupting a config we can't
	// see live. This is the last line of defence against all of that, plus
	// any hostname substitution that failed to fully strip the domain.
	if bytes.Contains(bytes.ToLower(out), []byte(domain)) {
		return nil, fmt.Errorf(
			"refusing to write output: domain %q is still present in the rendered bytes after hostname substitution — "+
				"check service, path, and originRequest fields (per-ingress and top-level) for a literal hostname on this domain",
			domain)
	}
	return out, nil
}

// substituteDomain replaces a trailing normalisedDomain match — the domain
// itself, or any subdomain of it — with DomainPlaceholder, matching
// case-insensitively but preserving the caller's casing of any leading
// subdomain labels that are kept. A hostname on any other domain is returned
// unchanged; UnexpectedDomains is what reports those, so an unknown domain is
// surfaced rather than mangled. normalisedDomain must already be the output
// of normaliseDomain.
func substituteDomain(hostname, normalisedDomain string) string {
	if hostname == "" {
		return ""
	}
	if !onDomain(hostname, normalisedDomain) {
		return hostname
	}
	if len(hostname) == len(normalisedDomain) {
		// Case-insensitive exact match against the apex domain itself.
		return DomainPlaceholder
	}
	// onDomain confirmed hostname ends with "."+normalisedDomain
	// (case-insensitively); casing never changes byte length, so slicing by
	// length is safe and keeps the caller's casing on the retained prefix.
	return hostname[:len(hostname)-len(normalisedDomain)] + DomainPlaceholder
}

// UnexpectedDomains returns hostnames that are not on publicDomain (matched
// case-insensitively via onDomain). These are written verbatim by Render —
// Render's byte guard will actually refuse to render them if they're carried
// in a field it can't safely rewrite, but callers should still surface this
// list so an operator is warned about a domain that doesn't belong at all,
// rather than just discovering a hard failure.
//
// Returns nil for a nil cfg or for a publicDomain that is empty once
// normalised — in both cases there is nothing meaningful to compare against.
func UnexpectedDomains(cfg *TunnelConfig, publicDomain string) []string {
	domain := normaliseDomain(publicDomain)
	if cfg == nil || domain == "" {
		return nil
	}
	var out []string
	for _, in := range cfg.Ingress {
		if in.Hostname == "" {
			continue // catch-all rule
		}
		if onDomain(in.Hostname, domain) {
			continue
		}
		out = append(out, in.Hostname)
	}
	return out
}
