package tunnel

import (
	"bytes"
	"errors"
	"fmt"
	"strings"
	"unicode/utf8"

	"gopkg.in/yaml.v3"
)

// ErrNoDomain is returned when rendering is attempted without a public domain
// to substitute. Rendering anyway would write real hostnames into a public repo.
var ErrNoDomain = errors.New("public_domain is empty: refusing to render, the real domain would be written verbatim")

// ErrNilConfig is returned by Render and UnexpectedDomains when called with a
// nil *TunnelConfig, so callers get a clear error instead of a panic.
var ErrNilConfig = errors.New("tunnel config is nil: nothing to render")

const renderHeader = `# Generated by ` + "`infra tunnel export`" + ` — DO NOT EDIT BY HAND.
#
# This is a MIRROR of a remotely-managed Cloudflare tunnel. The Zero Trust
# dashboard is the source of truth; editing this file changes nothing there.
#
# Regenerate:      infra tunnel export
# Check for drift: infra tunnel diff
#
# The real domain is replaced with ` + DomainPlaceholder + ` because this repo is
# public. The real value lives in ~/.config/infra/cloudflare.yml and CLAUDE.local.md.
`

// normaliseDomain lowercases publicDomain, trims surrounding whitespace, and
// strips leading/trailing dots, so that ".example.test", " EXAMPLE.test ", and
// "example.test" are all treated identically. Render and UnexpectedDomains
// each normalise once, at the top, and use only the returned value thereafter
// — nothing downstream should see the raw, untrimmed, case-sensitive input.
func normaliseDomain(publicDomain string) string {
	d := strings.ToLower(strings.TrimSpace(publicDomain))
	return strings.Trim(d, ".")
}

// onDomain reports whether hostname is normalisedDomain itself, or a subdomain
// of it (e.g. "*.example.test" or "foo.example.test" for domain
// "example.test"), compared case-insensitively because DNS names are not
// case-sensitive. A single trailing dot on hostname — the notation for an
// absolute FQDN, e.g. "portfolio.example.test." — is ignored for this
// comparison, since it is the same name either way; a leading dot is never
// valid here and is deliberately NOT stripped, so it keeps failing to match.
// normalisedDomain must already be the output of normaliseDomain.
//
// This is the single predicate substituteDomain and UnexpectedDomains both
// call. Do not re-implement this check anywhere else — a second copy that
// drifts from this one is exactly how a hostname ends up neither substituted
// nor reported, which is a silent leak.
func onDomain(hostname, normalisedDomain string) bool {
	if normalisedDomain == "" || hostname == "" {
		return false
	}
	h := strings.ToLower(strings.TrimSuffix(hostname, "."))
	return h == normalisedDomain || strings.HasSuffix(h, "."+normalisedDomain)
}

// Render serialises cfg to deterministic YAML with publicDomain replaced by
// DomainPlaceholder wherever it appears as a hostname.
//
// Determinism matters: `infra tunnel diff` compares bytes, so any instability
// here shows up as phantom drift. Struct field order fixes key order, and
// yaml.v3 sorts map keys, which covers originRequest and warp-routing.
//
// Hostname substitution is not the last word: after marshalling, the
// marshalled config body — never the header we author ourselves, which
// legitimately contains words like "infra" and "public" — is scanned
// byte-for-byte for the domain, and the render is rejected if it is still
// present anywhere. That closes the gap left by fields substituteDomain
// deliberately does not touch — Service, Path, and OriginRequest values —
// and by any hostname substitution that failed to fully strip the domain. If
// the domain does survive, the error names the specific field and value that
// carries it rather than a generic list, so the operator isn't sent hunting
// in the wrong place.
//
// That literal byte search only works when yaml.v3 emits the domain as a
// plain scalar. If any field's value is not valid UTF-8, yaml.v3 instead
// emits a "!!binary" tag followed by base64 of the raw bytes — e.g.
// `hdr: !!binary c3ViLmV4YW1wbGUudGVzdP/+` — and that base64 text is itself
// ordinary ASCII, so it contains no literal copy of the domain and passes
// utf8.Valid, while yaml.Unmarshal decodes it straight back to the real
// value on the next read. utf8.Valid(body) below does NOT catch this: the
// bytes it inspects are the base64 text, which is valid UTF-8 by
// construction, so that check can only ever fire on marshalled output that
// is invalid UTF-8 outright — not reachable today, since the per-hostname
// check further below already rejects an invalid-UTF-8 Hostname before
// marshalling ever happens, but kept as a backstop for any other field or a
// future producer of TunnelConfig. Closing the "!!binary" smuggling path
// itself requires a separate, explicit scan for that literal tag: its
// presence means some value could not be represented as text, so Render has
// no safe way to inspect what it hides and refuses to publish rather than
// guess.
func Render(cfg *TunnelConfig, publicDomain string) ([]byte, error) {
	domain := normaliseDomain(publicDomain)
	if domain == "" {
		return nil, ErrNoDomain
	}
	if cfg == nil {
		return nil, ErrNilConfig
	}

	sanitised := *cfg
	// Shallow copy: WarpRouting, the top-level OriginRequest, and each
	// Ingress[i].OriginRequest map below are shared by reference with the
	// caller's cfg, not deep-copied. That is safe only because nothing here
	// writes into any of those maps — only the value-typed Hostname field of
	// the per-element Ingress copy is rewritten. If a future change starts
	// writing into WarpRouting/OriginRequest (e.g. to sanitise a hostname
	// found there), it will silently mutate the caller's config too, which
	// would poison the later `diff` comparison. Deep-copy first if that's ever
	// needed.
	sanitised.Ingress = make([]Ingress, len(cfg.Ingress))
	for i, in := range cfg.Ingress {
		if !utf8.ValidString(in.Hostname) {
			return nil, fmt.Errorf(
				"ingress %d: hostname is not valid UTF-8 — refusing to render (yaml.v3 would encode it as base64, which decodes back to the real value and bypasses the byte guard)",
				i)
		}
		in.Hostname = substituteDomain(in.Hostname, domain)
		sanitised.Ingress[i] = in
	}
	body, err := yaml.Marshal(&sanitised)
	if err != nil {
		return nil, fmt.Errorf("marshal tunnel config: %w", err)
	}

	// Fail closed on non-UTF-8 output: the per-hostname check above closes the
	// only reachable path today (json.Unmarshal coerces bad bytes to U+FFFD
	// before a TunnelConfig is ever built), but this is a backstop for any
	// other field, and for any future yaml-decoded producer of TunnelConfig.
	if !utf8.Valid(body) {
		return nil, errors.New(
			"refusing to write output: rendered YAML is not valid UTF-8 — a field may contain bytes that yaml.v3 encoded as base64, which the domain byte guard cannot see through")
	}

	// Fail closed if yaml.v3 fell back to a non-literal ("!!binary") encoding
	// for any value. This is the check the comment above explains utf8.Valid
	// cannot do: the base64 payload a "!!binary" tag introduces is valid
	// UTF-8 by construction, so it neither trips the check above nor contains
	// a literal copy of the domain, yet it decodes straight back to the real
	// bytes on the next yaml.Unmarshal. Render cannot know whether the value
	// hidden behind the tag is safe, so it refuses to publish it at all.
	if bytes.Contains(body, []byte("!!binary")) {
		return nil, errors.New(
			"refusing to write output: a value could not be represented as text and was encoded as YAML binary (!!binary) — it cannot be safely checked for a leaked domain, so it cannot be published")
	}

	// Fail closed: if the real domain is still in the rendered body anywhere
	// — case-insensitively — after hostname substitution, do not return any
	// bytes. Deliberately scoped to body, not the header: the header is
	// authored by us and can legitimately contain words like "infra" or
	// "public" that would otherwise collide with a short configured domain.
	if bytes.Contains(bytes.ToLower(body), []byte(domain)) {
		return nil, fmt.Errorf(
			"refusing to write output: domain %q is still present after hostname substitution — found in %s",
			domain, locateDomain(&sanitised, domain))
	}
	out := append([]byte(renderHeader+"\n"), body...)
	return out, nil
}

// locateDomain reports which field of cfg — expected to be the sanitised,
// post-substitution copy — still carries a case-insensitive occurrence of
// domain, so Render's byte-guard error can name the right place instead of a
// generic list. It walks Ingress in order, checking Hostname, then Service,
// then Path on each entry, and returns as soon as it finds a match together
// with the offending value.
//
// domain must already be lowercase (the output of normaliseDomain). If none
// of those three fields carry it, the domain must be surviving in a field
// this function doesn't have visibility into the structure of — a per-ingress
// or top-level OriginRequest value, or WarpRouting — so it falls back to
// naming those as the remaining possibilities.
func locateDomain(cfg *TunnelConfig, domain string) string {
	for i, in := range cfg.Ingress {
		if strings.Contains(strings.ToLower(in.Hostname), domain) {
			return fmt.Sprintf("hostname of ingress[%d]: %q", i, in.Hostname)
		}
	}
	for i, in := range cfg.Ingress {
		if strings.Contains(strings.ToLower(in.Service), domain) {
			return fmt.Sprintf("service of ingress[%d]: %q", i, in.Service)
		}
	}
	for i, in := range cfg.Ingress {
		if strings.Contains(strings.ToLower(in.Path), domain) {
			return fmt.Sprintf("path of ingress[%d]: %q", i, in.Path)
		}
	}
	return "originRequest or warp-routing (per-ingress or top-level) — not inspected field-by-field"
}

// substituteDomain replaces the trailing normalisedDomain label(s) — the
// domain itself, or any subdomain of it — with DomainPlaceholder, matching
// case-insensitively (via onDomain) but preserving the caller's casing on any
// leading subdomain labels that are kept. A single trailing dot (the
// absolute-FQDN notation, e.g. "portfolio.example.test.") is stripped before
// matching and restored on the result; a leading dot is never valid here and
// is left alone, so it keeps failing to match, same as onDomain. A hostname
// on any other domain is returned unchanged — UnexpectedDomains is what
// reports those, so an unknown domain is surfaced rather than mangled.
// normalisedDomain must already be the output of normaliseDomain.
func substituteDomain(hostname, normalisedDomain string) string {
	if hostname == "" {
		return ""
	}
	h := hostname
	trailingDot := ""
	if strings.HasSuffix(h, ".") {
		h = h[:len(h)-1]
		trailingDot = "."
	}
	if !onDomain(h, normalisedDomain) {
		return hostname
	}
	// Find the cut point by walking back across normalisedDomain's own
	// dot-separated label count from literal '.' bytes in h, rather than
	// subtracting byte lengths: lowercasing does not preserve byte length for
	// every rune (U+0130 and U+212A are the two relevant exceptions — e.g. the
	// Kelvin sign U+212A is 3 bytes but lowercases to 1-byte 'k'), so a
	// length-based cut can land inside a multi-byte rune and hand back
	// invalid UTF-8. A literal '.' is always a safe cut point: byte 0x2E can
	// never appear as a continuation byte inside a multi-byte UTF-8 sequence.
	labels := strings.Count(normalisedDomain, ".") + 1
	prefix := trimTrailingLabels(h, labels)
	if prefix == "" {
		return DomainPlaceholder + trailingDot
	}
	return prefix + "." + DomainPlaceholder + trailingDot
}

// trimTrailingLabels removes the last n dot-separated labels from s (each
// preceded by its separating '.') and returns what remains, with no
// separator on the end. It walks back using literal '.' bytes, which are
// always safe UTF-8 cut points, so it never lands inside a multi-byte rune.
// Returns "" if s has n or fewer labels — i.e. the whole of s was consumed.
func trimTrailingLabels(s string, n int) string {
	rest := s
	for i := 0; i < n; i++ {
		idx := strings.LastIndexByte(rest, '.')
		if idx < 0 {
			return ""
		}
		rest = rest[:idx]
	}
	return rest
}

// UnexpectedDomains returns hostnames that are not on publicDomain (matched
// case-insensitively via onDomain). These are written verbatim by Render —
// Render's byte guard will actually refuse to render them if they're carried
// in a field it can't safely rewrite, but callers should still surface this
// list so an operator is warned about a domain that doesn't belong at all,
// rather than just discovering a hard failure.
//
// Returns nil for a nil cfg or for a publicDomain that is empty once
// normalised — in both cases there is nothing meaningful to compare against.
func UnexpectedDomains(cfg *TunnelConfig, publicDomain string) []string {
	domain := normaliseDomain(publicDomain)
	if cfg == nil || domain == "" {
		return nil
	}
	var out []string
	for _, in := range cfg.Ingress {
		if in.Hostname == "" {
			continue // catch-all rule
		}
		if onDomain(in.Hostname, domain) {
			continue
		}
		out = append(out, in.Hostname)
	}
	return out
}
