package tunnel

import (
	"errors"
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"
)

// ErrNoDomain is returned when rendering is attempted without a public domain
// to substitute. Rendering anyway would write real hostnames into a public repo.
var ErrNoDomain = errors.New("public_domain is empty: refusing to render, the real domain would be written verbatim")

const renderHeader = `# Generated by ` + "`infra tunnel export`" + ` — DO NOT EDIT BY HAND.
#
# This is a MIRROR of a remotely-managed Cloudflare tunnel. The Zero Trust
# dashboard is the source of truth; editing this file changes nothing there.
#
# Regenerate:      infra tunnel export
# Check for drift: infra tunnel diff
#
# The real domain is replaced with ` + DomainPlaceholder + ` because this repo is
# public. The real value lives in ~/.config/infra/cloudflare.yml and CLAUDE.local.md.
`

// Render serialises cfg to deterministic YAML with publicDomain replaced by
// DomainPlaceholder.
//
// Determinism matters: `infra tunnel diff` compares bytes, so any instability
// here shows up as phantom drift. Struct field order fixes key order, and
// yaml.v3 sorts map keys, which covers originRequest and warp-routing.
func Render(cfg *TunnelConfig, publicDomain string) ([]byte, error) {
	if strings.TrimSpace(publicDomain) == "" {
		return nil, ErrNoDomain
	}
	sanitised := *cfg
	sanitised.Ingress = make([]Ingress, len(cfg.Ingress))
	for i, in := range cfg.Ingress {
		in.Hostname = substituteDomain(in.Hostname, publicDomain)
		sanitised.Ingress[i] = in
	}
	body, err := yaml.Marshal(&sanitised)
	if err != nil {
		return nil, fmt.Errorf("marshal tunnel config: %w", err)
	}
	return append([]byte(renderHeader+"\n"), body...), nil
}

// substituteDomain replaces a trailing publicDomain with DomainPlaceholder.
// A hostname on any other domain is returned unchanged — UnexpectedDomains is
// what reports those, so that an unknown domain is surfaced rather than mangled.
func substituteDomain(hostname, publicDomain string) string {
	if hostname == "" {
		return ""
	}
	if hostname == publicDomain {
		return DomainPlaceholder
	}
	if strings.HasSuffix(hostname, "."+publicDomain) {
		return strings.TrimSuffix(hostname, publicDomain) + DomainPlaceholder
	}
	return hostname
}

// UnexpectedDomains returns hostnames that are not on publicDomain. These are
// written verbatim by Render, so callers must warn about them.
func UnexpectedDomains(cfg *TunnelConfig, publicDomain string) []string {
	var out []string
	for _, in := range cfg.Ingress {
		if in.Hostname == "" {
			continue // catch-all rule
		}
		if in.Hostname == publicDomain || strings.HasSuffix(in.Hostname, "."+publicDomain) {
			continue
		}
		out = append(out, in.Hostname)
	}
	return out
}
